### ISSUE TITLE
Hacer migraciones de la base de datos

### ISSUE THREAD

**Issue by abrilgzz** [ProyectoIntegrador2018/conexion_tec#73]
## Nombre de Tarea
Hacer migraciones de la base de datos

## Descripción de Tarea
Crear los archivos necesarios para modificar la base de datos conforme al nuevo esquema.

[Data Base Model.pdf](https://github.com/ProyectoIntegrador2018/conexion_tec/files/2907596/Data.Base.Model.pdf)

## Conversación
Es necesario cambiar la base de datos para poder hacer la implementación de la funcionalidad de los distintos roles de usuarios.

## To-DO
- [x] Quitar columna 'name', 'enrollment', 'project_id' y 'email' de Student
- [x] Renombrar columna 'major' a 'major_id' de Student
- [x] Quitar columnas 'active', 'assistance', 'num_assignments', 'num_evaluations', 'reason', 'score' de Project
- [x] Agregar columnas 'selection_score : decimal', 'evaluation_score : decimal', 'professor_id', 'student_id' (owner), 'edition_id' a Project
- [x] Renombrar columnas 'status' a 'status_id', 'field' a 'field_id', 'client' a  'client_id' de Project
- [x] Quitar 'name', 'enrollment', 'course_code', 'email' de Professor
- [x] Renombrar columna 'department' a 'department_id' de Professor
- [x] Quitar 'name' de Judge
- [x] Renombrar 'department' a 'department_id' de Judge
- [x] Agregar tabla de Assignment(project_id, judge_id, evaluation_id)
- [x] Agregar tabla de Client(type)
- [x] Agregar tabla de Field(name)
- [x] Agregar tabla de Member(email, major_id, name, project_id)
- [x] Agregar tabla de Edition(registration_open : date, registration_closed : date, video_open : date, video_closed : date)
- [x] Agregar tabla de Status(type)
- [x] Agregar tabla de Major(name)
- [x] Agregar tabla de Department(name)

## Criterios de aceptación
- [x] La base de datos concuerda con el modelo definido
