### ISSUE TITLE
Modificar el esquema de la base de datos

### ISSUE THREAD

**Issue by ssandoval95** [ProyectoIntegrador2018/conexion_tec#83]
## Nombre de Tarea
Modificar el esquema de la base de datos

## Descripción de Tarea
Agregar las tablas y las relaciones faltantes en el esquema de la base de datos

## Conversación
Modificar el esquema para poder cumplir con los requisitos planteados con el cliente

## To-do
- [x] Agregar columna 'name' a User
- [x] Agregar catálogo de departamentos
- [x] Agregar catálogo de carreras
- [x] Agregar catálogo de estatus
- [x] Revisar que los otros catálogos estén (tipo de proyecto, categoría de proyectos, tipo de cliente, áreas estratégicas)

## Criterios de aceptación
- [x] El esquema corresponde a lo acordado como equipo
- [x] Validado por todos los miembros

**Comment by PQbiit** [comment]
Amigos ya está listo el modelo corregido de la DB por favor revísenlo para que todos estemos en el mismo canal y poder marcar como done la tarea

Data Base Model:
https://drive.google.com/file/d/1nEc5jC_-HQIlKJWGyS8g2eUAS1aioLS3/view?usp=sharing
